" ======== BEGIN DEFAULTS ========

runtime! debian.vim

if has("syntax")
  syntax on
endif

" ======== END DEFAULTS ========

" jump to the last position when reopening a file
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

filetype plugin indent on

let vimDir = '\$HOME/.vim'
if stridx(&runtimepath, expand(vimDir)) == -1
  " vimDir is not on runtimepath, add it
  let &runtimepath.=','.vimDir
endif
" Keep undo history across sessions by storing it in a file
if has('persistent_undo')
    let myUndoDir = expand(vimDir . '/undodir')
    " Create dirs
    call system('mkdir ' . vimDir)
    call system('mkdir ' . myUndoDir)
    let &undodir = myUndoDir
    set undofile
endif
command W w " I often mistype this
set encoding=utf-8
set mouse=
set ttymouse=
set undolevels=10000
set undoreload=10000
set paste

set showcmd
set showmatch
set ignorecase
set smartcase
set incsearch
set hidden
