name: Execute and publish image autobuilds
on:
  push:
    branches:
      - master

env:
  AUTOBUILD_OS_PROJECT: 37e471bf9f584ebd986acc44639a5bd4
  OS_CLOUD: openstack

jobs:
  install-deps:
    runs-on: self-hosted
    steps:
      - name: Install apt dependencies
        run: |
          sudo apt update &&
          sudo apt install -y python3-virtualenv \
                              debian-archive-keyring \
                              python3.10-venv \
                              python3-pip \
                              btrfs-progs \
                              qemu-system \
                              qemu-utils \
                              squashfs-tools \
                              multipath-tools \
                              debootstrap dpkg

      - name: Install pip dependencies
        run: |
          sudo pip install python-openstackclient \
                           diskimage-builder

  build-and-publish:
    runs-on: self-hosted
    needs: ["install-deps"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize clouds.yaml
        run: |
          echo "${{ secrets.clouds }}" > clouds.yaml

      - name: Build Mekstack Ubuntu
        run: |
          ELEMENTS_PATH=elements diskimage-builder ubuntu.yaml

      - name: Publish Mekstack Ubuntu
        run: |
          export ID=$(
            openstack image create \
                --property description="Built on $(date +'%d %B'). Default user: ubuntu" \
                --property hw_qemu_guest_agent=yes \
                --property autobuild=yes \
                --container-format bare \
                --public \
                --project $AUTOBUILD_OS_PROJECT \
                --min-disk 5 \
                --min-ram 1024 \
                --disk-format qcow2 \
                --file ubuntu.qcow2 \
                -f value -c id \
                "Mekstack Ubuntu 22.04.3 LTS"
              )
          openstack image list --project $AUTOBUILD_OS_PROJECT --name "Mekstack Ubuntu 22.04.3 LTS" -f value -c ID |
          grep -v $ID |
          xargs -L1 --no-run-if-empty openstack image set --public --hidden
        shell: bash

      - name: Build Mekstack Ubuntu minimal
        run: |
          ELEMENTS_PATH=elements diskimage-builder ubuntu-minimal.yaml

      - name: Publish Mekstack Ubuntu minimal
        run: |
          export ID=$(
            openstack image create \
                --property description="Built on $(date +'%d %B'). Default user: ubuntu" \
                --property hw_qemu_guest_agent=yes \
                --property autobuild=yes \
                --container-format bare \
                --public \
                --project $AUTOBUILD_OS_PROJECT \
                --min-disk 3 \
                --min-ram 512 \
                --disk-format qcow2 \
                --file ubuntu-minimal.qcow2 \
                -f value -c id \
                "Mekstack Ubuntu 22.04.3 LTS (minimal)"
            )
          openstack image list --project $AUTOBUILD_OS_PROJECT --name 'Mekstack Ubuntu 22.04.3 LTS (minimal)' -f value -c ID |
          grep -v $ID |
          xargs -L1 --no-run-if-empty openstack image set --public --hidden
        shell: bash

      - name: Build Mekstack Debian
        run: |
          ELEMENTS_PATH=elements diskimage-builder debian.yaml

      - name: Publish Mekstack Debian
        run: |
          export ID=$(
            openstack image create \
                --property description="Built on $(date +'%d %B'). Default user: debian" \
                --property hw_qemu_guest_agent=yes \
                --property autobuild=yes \
                --container-format bare \
                --public \
                --project $AUTOBUILD_OS_PROJECT \
                --min-disk 3 \
                --min-ram 512 \
                --disk-format qcow2 \
                --file debian.qcow2 \
                -f value -c id \
                "Mekstack Debian Bookworm 12"
            )
          openstack image list --project $AUTOBUILD_OS_PROJECT --name "Mekstack Debian Bookworm 12" -f value -c ID |
          grep -v $ID |
          xargs -L1 --no-run-if-empty openstack image set --public --hidden
        shell: bash
